using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IdentityApplication.Migrations
{
    /// <inheritdoc />
    public partial class SeedData : Migration
    {
        private string UserRoleId = Guid.NewGuid().ToString();
        private string AdminRoleId = Guid.NewGuid().ToString();
        private string AdminId = Guid.NewGuid().ToString();
        private string UserId = Guid.NewGuid().ToString();
        private string LocationId = Guid.NewGuid().ToString();
        private string CategoryId = Guid.NewGuid().ToString();

        private string employeeMenu = Guid.NewGuid().ToString();
        private string userMenu = Guid.NewGuid().ToString();
        private string categoryMenu = Guid.NewGuid().ToString();
        private string subcategoryMenu = Guid.NewGuid().ToString();
        private string menu = Guid.NewGuid().ToString();

        private string createEmployeeSubMenu = Guid.NewGuid().ToString();
        private string listEmployeeSubMenu = Guid.NewGuid().ToString();
        private string profileUserSubMenu = Guid.NewGuid().ToString();

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            SeedLocations(migrationBuilder);
            SeedDepartment(migrationBuilder);
            SeedCategory(migrationBuilder);
            SeedSubCategory(migrationBuilder);
            SeedRolesSQL(migrationBuilder);
            SeedUser(migrationBuilder);
            SeedUserRoles(migrationBuilder);
            SeedClaims(migrationBuilder);
            SeedMenu(migrationBuilder);
            SeedSubMenu(migrationBuilder);
            SeedSubMenuRole(migrationBuilder);
        }
        private void SeedRolesSQL(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"INSERT INTO [AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp])
                VALUES ('{AdminRoleId}', 'Administrator', 'ADMINISTRATOR', null);");

            migrationBuilder.Sql($@"INSERT INTO [AspNetRoles] ([Id], [Name], [NormalizedName], [ConcurrencyStamp])
                VALUES ('{UserRoleId}', 'User', 'USER', null);");
        }
        private void SeedUser(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [AspNetUsers] ([Id], [UserName], [LocationId], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) 
                VALUES ('{AdminId}', 'admin@test.com', '{LocationId}', 'ADMIN@TEST.COM', 'admin@test.com', 'ADMIN@TEST.COM', 0, 'AQAAAAIAAYagAAAAEAIoVtgbc8xCgaF/0Uor35PW8MmYnEIjPJLPBKQlW/1Q0YZGQnsGru3FZrws9lv9Bg==', 'YUPAFWNGZI2UC5FOITC7PX5J7XZTAZAA', '9337b27a-86df-425c-a68b-10e97e15d4ae', NULL, 0, 0, NULL, 1, 0)");

            migrationBuilder.Sql($@"
                INSERT INTO [AspNetUsers] ([Id], [UserName], [LocationId], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) 
                VALUES ('{UserId}', 'user@test.com', '{LocationId}', 'USER@TEST.COM', 'user@test.com', 'USER@TEST.COM', 0, 'AQAAAAIAAYagAAAAEAIoVtgbc8xCgaF/0Uor35PW8MmYnEIjPJLPBKQlW/1Q0YZGQnsGru3FZrws9lv9Bg==', 'YUPAFWNGZI2UC5FOITC7PX5J7XZTAZAA', '751920ce-2459-4f57-95de-2bf30c1205f5', NULL, 0, 0, NULL, 1, 0)");
        }
        private void SeedUserRoles(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [AspNetUserRoles] ([UserId], [RoleId])
                VALUES ('{UserId}', '{UserRoleId}');");

            migrationBuilder.Sql($@"
                INSERT INTO [AspNetUserRoles] ([UserId], [RoleId])
                VALUES ('{AdminId}', '{AdminRoleId}');");
        }
        private void SeedLocations(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [Location] VALUES 
                ('{LocationId}', 'NOLIMIT OGF'),
                (NEWID(), 'HYDE PARK'),
                (NEWID(), 'CCC'),
                (NEWID(), 'PANADURA'),
                (NEWID(), 'NEGOMBO NOLIMIT'),
                (NEWID(), 'DEHIWALA GENTS'),
                (NEWID(), 'MAHARAGAMA'),
                (NEWID(), '7MP'),
                (NEWID(), 'BORELLA'),
                (NEWID(), 'NUGEGODA'),
                (NEWID(), 'WELLAWATTE IMAGE'),
                (NEWID(), 'KEGALLE'),
                (NEWID(), 'KANDY'),
                (NEWID(), 'RATMALANA'),
                (NEWID(), 'KURUNEGALA'),
                (NEWID(), 'NEGOMBO 424'),
                (NEWID(), 'RATNAPURA'),
                (NEWID(), 'WATTALA'),
                (NEWID(), 'DEHIWALA LADIES'),
                (NEWID(), 'WELLAWATTE'),
                (NEWID(), 'NOLIMIT KIDS OGF'),
                (NEWID(), 'MOUNT LAVINIA'),
                (NEWID(), 'KCC');");
        }
        private void SeedDepartment(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [Department] VALUES 
                (NEWID(), 'GENTS'),
                (NEWID(), 'LADIES'),
                (NEWID(), 'ACCESSORIES'),
                (NEWID(), 'HOMEWARE'),
                (NEWID(), 'KIDS');");
        }
        private void SeedCategory(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [Category] VALUES 
                ('{CategoryId}', 'Girls'),
                (NEWID(), N'Maternity wear'),
                (NEWID(), N'STORAGE'),
                (NEWID(), N'HOME TEXTILES'),
                (NEWID(), N'Sleep wear'),
                (NEWID(), N'Baby Care Accessories'),
                (NEWID(), N'Boys Accessories'),
                (NEWID(), N'SPORTS ACCESSORIES'),
                (NEWID(), N'Color Cosmetics'),
                (NEWID(), N'HOME ESSENTIALS'),
                (NEWID(), N'Boys'),
                (NEWID(), N'Toys'),
                (NEWID(), N'Winter wear'),
                (NEWID(), N'Bath ware'),
                (NEWID(), N'Undergarments'),
                (NEWID(), N'Phone Accessories'),
                (NEWID(), N'KITCHEN ESSENTIALS'),
                (NEWID(), N'Swim & beach waer'),
                (NEWID(), N'Formal wear'),
                (NEWID(), N'HOME DÉCOR'),
                (NEWID(), N'Casual wear'),
                (NEWID(), N'DINING'),
                (NEWID(), N'Gents Accessories'),
                (NEWID(), N'Bedding'),
                (NEWID(), N'Bags'),
                (NEWID(), N'HOME APPLIANCES'),
                (NEWID(), N'Ethnic wear'),
                (NEWID(), N'FURNITURES'),
                (NEWID(), N'Baby Girls'),
                (NEWID(), N'Travel wear'),
                (NEWID(), N'Skin Care'),
                (NEWID(), N'Foot Wear'),
                (NEWID(), N'HAIR CARE'),
                (NEWID(), N'Newborn'),
                (NEWID(), N'SHAPE WEAR'),
                (NEWID(), N'Shades'),
                (NEWID(), N'Personal Care Accessories'),
                (NEWID(), N'Baby Boys'),
                (NEWID(), N'JEWELLERY'),
                (NEWID(), N'Ladies Accessories'),
                (NEWID(), N'Hair Accessories'),
                (NEWID(), N'Party wear'),
                (NEWID(), N'Infants  Unisex'),
                (NEWID(), N'Wallet & Purse'),
                (NEWID(), N'Sports & leisure wear'),
                (NEWID(), N'Fragrance'),
                (NEWID(), N'Stationaries'),
                (NEWID(), N'Home ware'),
                (NEWID(), N'Functional'),
                (NEWID(), N'Kids accessories'),
                (NEWID(), N'Lingerie'),
                (NEWID(), N'Girls Accessories'),
                (NEWID(), N'Home Accessories');");
        }
        private void SeedSubCategory(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [SubCategory] VALUES
                (NEWID(), N'T-shirt','{CategoryId}'),
                (NEWID(), N'Mitten','{CategoryId}'),
                (NEWID(), N'Nail Cutter Set','{CategoryId}'),
                (NEWID(), N'Padded panty','{CategoryId}'),
                (NEWID(), N'EYE LASHES','{CategoryId}'),
                (NEWID(), N'Shampoo','{CategoryId}'),
                (NEWID(), N'Desk & Chair','{CategoryId}'),
                (NEWID(), N'Feeding Chair','{CategoryId}'),
                (NEWID(), N'Cap Hijab','{CategoryId}'),
                (NEWID(), N'Tunic top','{CategoryId}'),
                (NEWID(), N'Swim Ring','{CategoryId}'),
                (NEWID(), N'Eye Liner','{CategoryId}'),
                (NEWID(), N'ORNAMENT','{CategoryId}'),
                (NEWID(), N'PADDED SHORT','{CategoryId}'),
                (NEWID(), N'Sleeper suit','{CategoryId}'),
                (NEWID(), N'Bumper','{CategoryId}'),
                (NEWID(), N'MAANG TIKKA','{CategoryId}'),
                (NEWID(), N'RULER','{CategoryId}'),
                (NEWID(), N'Thermometer','{CategoryId}'),
                (NEWID(), N'SKIN CLEAR','{CategoryId}'),
                (NEWID(), N'Finger ring','{CategoryId}'),
                (NEWID(), N'WAFFLE MAKER','{CategoryId}'),
                (NEWID(), N'Hankey','{CategoryId}'),
                (NEWID(), N'Lace bra','{CategoryId}'),
                (NEWID(), N'PIPING BAG','{CategoryId}'),
                (NEWID(), N'Night cream','{CategoryId}'),
                (NEWID(), N'Cleansing milk','{CategoryId}'),
                (NEWID(), N'BABY BATH NET','{CategoryId}'),
                (NEWID(), N'Midi bra','{CategoryId}'),
                (NEWID(), N'Necklace','{CategoryId}'),
                (NEWID(), N'Velour','{CategoryId}'),
                (NEWID(), N'SEWING SET','{CategoryId}'),
                (NEWID(), N'Powder puff','{CategoryId}'),
                (NEWID(), N'PIPING SYRINGE','{CategoryId}'),
                (NEWID(), N'Pedicure File','{CategoryId}'),
                (NEWID(), N'Lip Liner Pencil','{CategoryId}'),
                (NEWID(), N'Baby Pool','{CategoryId}'),
                (NEWID(), N'NAPPY PAD','{CategoryId}'),
                (NEWID(), N'Car seat','{CategoryId}'),
                (NEWID(), N'Cream','{CategoryId}'),
                (NEWID(), N'Nasal aspirator','{CategoryId}'),
                (NEWID(), N'Kettle','{CategoryId}'),
                (NEWID(), N'Cushion cover','{CategoryId}'),
                (NEWID(), N'Suit','{CategoryId}'),
                (NEWID(), N'HAIR PIN','{CategoryId}'),
                (NEWID(), N'MOISTURIZING GLOVES','{CategoryId}'),
                (NEWID(), N'Diaper','{CategoryId}'),
                (NEWID(), N'Fair Intense','{CategoryId}'),
                (NEWID(), N'KITCHEN ACCESSORIES','{CategoryId}'),
                (NEWID(), N'TRAVEL BOTTLE','{CategoryId}'),
                (NEWID(), N'HAIR DRYER HOLDER','{CategoryId}'),
                (NEWID(), N'Cake Plate','{CategoryId}'),
                (NEWID(), N'JEWELLERY BOX','{CategoryId}'),
                (NEWID(), N'Eye Definer','{CategoryId}'),
                (NEWID(), N'COT MOBILE','{CategoryId}'),
                (NEWID(), N'Razor','{CategoryId}'),
                (NEWID(), N'Legging','{CategoryId}'),
                (NEWID(), N'Under skirt','{CategoryId}'),
                (NEWID(), N'THIGH SUPPORT','{CategoryId}'),
                (NEWID(), N'Hand wash','{CategoryId}'),
                (NEWID(), N'SPRAY BOTTLE','{CategoryId}'),
                (NEWID(), N'Comb & brush','{CategoryId}'),
                (NEWID(), N'Newborn Toy','{CategoryId}'),
                (NEWID(), N'Shoe Rack','{CategoryId}'),
                (NEWID(), N'TPR Handle','{CategoryId}'),
                (NEWID(), N'MOULD','{CategoryId}'),
                (NEWID(), N'Anti-dandruff & shampoo','{CategoryId}'),
                (NEWID(), N'Baby talc','{CategoryId}'),
                (NEWID(), N'Under Short','{CategoryId}'),
                (NEWID(), N'MAKE-UP STICK','{CategoryId}'),
                (NEWID(), N'Shaving Cream','{CategoryId}'),
                (NEWID(), N'BABY WRAPPER','{CategoryId}'),
                (NEWID(), N'Lipstick','{CategoryId}'),
                (NEWID(), N'ICE CREAM BOWL','{CategoryId}'),
                (NEWID(), N'CLOTH RACK','{CategoryId}'),
                (NEWID(), N'HAND WARMER PILLOW','{CategoryId}'),
                (NEWID(), N'Cloth Hanger','{CategoryId}'),
                (NEWID(), N'Beach Towel','{CategoryId}'),
                (NEWID(), N'COLOUR PELETTE','{CategoryId}'),
                (NEWID(), N'Walker','{CategoryId}'),
                (NEWID(), N'Nighty house coat','{CategoryId}'),
                (NEWID(), N'YOGA MAT','{CategoryId}'),
                (NEWID(), N'SPICE BOTTLE SET','{CategoryId}'),
                (NEWID(), N'ROCKING CHAIR','{CategoryId}'),
                (NEWID(), N'DECORATIVE MAGNET','{CategoryId}'),
                (NEWID(), N'SERUM','{CategoryId}'),
                (NEWID(), N'Foot Rasp','{CategoryId}'),
                (NEWID(), N'Kickboard','{CategoryId}'),
                (NEWID(), N'Aloe','{CategoryId}'),
                (NEWID(), N'SHARPNER','{CategoryId}'),
                (NEWID(), N'LEMON SQUEEZER','{CategoryId}'),
                (NEWID(), N'Padded bra','{CategoryId}'),
                (NEWID(), N'Rattle','{CategoryId}'),
                (NEWID(), N'Storage Box','{CategoryId}'),
                (NEWID(), N'Starter Set','{CategoryId}'),
                (NEWID(), N'WAIST BELT','{CategoryId}'),
                (NEWID(), N'SIDE BAG-C','{CategoryId}'),
                (NEWID(), N'Cycling Short','{CategoryId}'),
                (NEWID(), N'HOUSE COAT MATERIAL','{CategoryId}'),
                (NEWID(), N'Color stay Makeup- Soft flex','{CategoryId}'),
                (NEWID(), N'School bag','{CategoryId}'),
                (NEWID(), N'Cuticle Sticks','{CategoryId}'),
                (NEWID(), N'Stroller','{CategoryId}'),
                (NEWID(), N'Girdle short','{CategoryId}'),
                (NEWID(), N'Foundation','{CategoryId}'),
                (NEWID(), N'Eye shadow Brush','{CategoryId}'),
                (NEWID(), N'EYEBROW BRUSH','{CategoryId}'),
                (NEWID(), N'DHOTI','{CategoryId}'),
                (NEWID(), N'Book','{CategoryId}'),
                (NEWID(), N'HOOK','{CategoryId}'),
                (NEWID(), N'Baby Bag','{CategoryId}'),
                (NEWID(), N'Sun Cream','{CategoryId}'),
                (NEWID(), N'Blanket sleeper','{CategoryId}'),
                (NEWID(), N'TABLE LAMP','{CategoryId}'),
                (NEWID(), N'ROCKER','{CategoryId}'),
                (NEWID(), N'INDIAN HOUSE COAT','{CategoryId}'),
                (NEWID(), N'Educational toy','{CategoryId}'),
                (NEWID(), N'Belt','{CategoryId}'),
                (NEWID(), N'CRAYON','{CategoryId}'),
                (NEWID(), N'EYELASH CURLER','{CategoryId}'),
                (NEWID(), N'Milk powder container','{CategoryId}'),
                (NEWID(), N'JAR','{CategoryId}'),
                (NEWID(), N'Swim dress','{CategoryId}'),
                (NEWID(), N'Wet wipers','{CategoryId}'),
                (NEWID(), N'ANKLE SUPPORT','{CategoryId}'),
                (NEWID(), N'MATTRESS','{CategoryId}'),
                (NEWID(), N'Bed sheet','{CategoryId}'),
                (NEWID(), N'TERMAL WEAR','{CategoryId}'),
                (NEWID(), N'CLEAN UP','{CategoryId}'),
                (NEWID(), N'EYE GROOMING KIT','{CategoryId}'),
                (NEWID(), N'Pendant','{CategoryId}'),
                (NEWID(), N'Maxi Buffer','{CategoryId}'),
                (NEWID(), N'Cream Powder','{CategoryId}'),
                (NEWID(), N'Apron','{CategoryId}'),
                (NEWID(), N'SWIM PADDLE','{CategoryId}'),
                (NEWID(), N'Purse','{CategoryId}'),
                (NEWID(), N'Buffing Block','{CategoryId}'),
                (NEWID(), N'COAT KIT','{CategoryId}'),
                (NEWID(), N'Top speed Man','{CategoryId}'),
                (NEWID(), N'Cufflinks','{CategoryId}'),
                (NEWID(), N'WIPES','{CategoryId}'),
                (NEWID(), N'PRAYER RUG','{CategoryId}'),
                (NEWID(), N'Music & Sound','{CategoryId}'),
                (NEWID(), N'Goggles','{CategoryId}'),
                (NEWID(), N'PLAY MAT','{CategoryId}'),
                (NEWID(), N'NATIONAL FLAG','{CategoryId}'),
                (NEWID(), N'Wallet','{CategoryId}'),
                (NEWID(), N'MATTRESS PROTECTOR','{CategoryId}'),
                (NEWID(), N'Petticoat','{CategoryId}'),
                (NEWID(), N'MEASURING CUP','{CategoryId}'),
                (NEWID(), N'Bath robe','{CategoryId}'),
                (NEWID(), N'BODY SUIT','{CategoryId}'),
                (NEWID(), N'SWIM BALL','{CategoryId}'),
                (NEWID(), N'Sandals','{CategoryId}'),
                (NEWID(), N'MASK BAND','{CategoryId}'),
                (NEWID(), N'COTTON BALLS','{CategoryId}'),
                (NEWID(), N'Tea Set','{CategoryId}'),
                (NEWID(), N'FINS','{CategoryId}'),
                (NEWID(), N'Pijama','{CategoryId}'),
                (NEWID(), N'Panty set','{CategoryId}'),
                (NEWID(), N'HIGH LIGHTER','{CategoryId}'),
                (NEWID(), N'Pumice Mouse','{CategoryId}'),
                (NEWID(), N'Funny toy','{CategoryId}'),
                (NEWID(), N'False Eyelashes','{CategoryId}'),
                (NEWID(), N'Fairness Cream','{CategoryId}'),
                (NEWID(), N'STATIONARY HOLDER','{CategoryId}'),
                (NEWID(), N'Sanitary panty','{CategoryId}'),
                (NEWID(), N'Gift pack','{CategoryId}'),
                (NEWID(), N'Soap case','{CategoryId}'),
                (NEWID(), N'MAKE-UP SPONGE','{CategoryId}'),
                (NEWID(), N'Blanket','{CategoryId}'),
                (NEWID(), N'Feeding bra','{CategoryId}'),
                (NEWID(), N'Perfume','{CategoryId}'),
                (NEWID(), N'Trouser','{CategoryId}'),
                (NEWID(), N'JAMMER','{CategoryId}'),
                (NEWID(), N'Caftan','{CategoryId}'),
                (NEWID(), N'Salwar','{CategoryId}'),
                (NEWID(), N'Leotard','{CategoryId}'),
                (NEWID(), N'Deo Roll On','{CategoryId}'),
                (NEWID(), N'Hair oil','{CategoryId}'),
                (NEWID(), N'LIQUID CLEANSER','{CategoryId}'),
                (NEWID(), N'HOODIE','{CategoryId}'),
                (NEWID(), N'ERASER','{CategoryId}'),
                (NEWID(), N'Baby Wash','{CategoryId}'),
                (NEWID(), N'SWADDLE','{CategoryId}'),
                (NEWID(), N'PILLOW COVER','{CategoryId}'),
                (NEWID(), N'Glass Set','{CategoryId}'),
                (NEWID(), N'Dinner set','{CategoryId}'),
                (NEWID(), N'BATHER','{CategoryId}'),
                (NEWID(), N'FACE PACK','{CategoryId}'),
                (NEWID(), N'VASE','{CategoryId}'),
                (NEWID(), N'FLASHLIGHT','{CategoryId}'),
                (NEWID(), N'Spoon','{CategoryId}'),
                (NEWID(), N'Earring','{CategoryId}'),
                (NEWID(), N'Lip Gloss','{CategoryId}'),
                (NEWID(), N'PRESSED POWDER','{CategoryId}'),
                (NEWID(), N'Grater','{CategoryId}'),
                (NEWID(), N'Silicon Mould','{CategoryId}'),
                (NEWID(), N'HOME SAFETY GUARDS','{CategoryId}'),
                (NEWID(), N'Shrug','{CategoryId}'),
                (NEWID(), N'STICKY NOTE STICKER','{CategoryId}'),
                (NEWID(), N'Bowl Set','{CategoryId}'),
                (NEWID(), N'4Way Super Block','{CategoryId}'),
                (NEWID(), N'Skin toner','{CategoryId}'),
                (NEWID(), N'Baby Set','{CategoryId}'),
                (NEWID(), N'Manicure','{CategoryId}'),
                (NEWID(), N'Towel','{CategoryId}'),
                (NEWID(), N'Hair cream','{CategoryId}'),
                (NEWID(), N'CUP SET','{CategoryId}'),
                (NEWID(), N'Bath Set','{CategoryId}'),
                (NEWID(), N'Feeder','{CategoryId}'),
                (NEWID(), N'HOODED JACKET','{CategoryId}'),
                (NEWID(), N'Skirt and Blouse','{CategoryId}'),
                (NEWID(), N'Chair','{CategoryId}'),
                (NEWID(), N'Nail file','{CategoryId}'),
                (NEWID(), N'Talc','{CategoryId}'),
                (NEWID(), N'COSMATIC TOOL KIT','{CategoryId}'),
                (NEWID(), N'Cup','{CategoryId}'),
                (NEWID(), N'Coffee Set','{CategoryId}'),
                (NEWID(), N'Cardigan','{CategoryId}'),
                (NEWID(), N'Compact Paddle','{CategoryId}'),
                (NEWID(), N'TRAVELLING','{CategoryId}'),
                (NEWID(), N'TIN CUTTER','{CategoryId}'),
                (NEWID(), N'Shoes-B','{CategoryId}'),
                (NEWID(), N'Sandals-U','{CategoryId}'),
                (NEWID(), N'Roll On','{CategoryId}'),
                (NEWID(), N'Hair band','{CategoryId}'),
                (NEWID(), N'Hanger Set','{CategoryId}'),
                (NEWID(), N'ELBOW SUPPORT','{CategoryId}'),
                (NEWID(), N'Shoes','{CategoryId}'),
                (NEWID(), N'EYE BROW BRUSH','{CategoryId}'),
                (NEWID(), N'NAIL TIPS','{CategoryId}'),
                (NEWID(), N'Facial foam','{CategoryId}'),
                (NEWID(), N'Lunch box','{CategoryId}'),
                (NEWID(), N'COMPRESSED DRY TISSUE','{CategoryId}'),
                (NEWID(), N'Glove','{CategoryId}'),
                (NEWID(), N'WRISTBAND','{CategoryId}'),
                (NEWID(), N'H & B Lotion','{CategoryId}'),
                (NEWID(), N'Back pack','{CategoryId}'),
                (NEWID(), N'WATER COLOURS','{CategoryId}'),
                (NEWID(), N'KNEE SUPPORT','{CategoryId}'),
                (NEWID(), N'Girdle panty','{CategoryId}'),
                (NEWID(), N'BOTTLE COVER','{CategoryId}'),
                (NEWID(), N'Fry Pan','{CategoryId}'),
                (NEWID(), N'Fashion Colour','{CategoryId}'),
                (NEWID(), N'FOOD WARMER','{CategoryId}'),
                (NEWID(), N'PASTRY ROLLER CUTTER','{CategoryId}'),
                (NEWID(), N'CARD HOLDER','{CategoryId}'),
                (NEWID(), N'Jacket','{CategoryId}'),
                (NEWID(), N'SPATULAR','{CategoryId}'),
                (NEWID(), N'Hair gel','{CategoryId}'),
                (NEWID(), N'Make-up/Shaving','{CategoryId}'),
                (NEWID(), N'Tray','{CategoryId}'),
                (NEWID(), N'COMPASSES SET','{CategoryId}'),
                (NEWID(), N'PASTRY WHEEL','{CategoryId}'),
                (NEWID(), N'Vest','{CategoryId}'),
                (NEWID(), N'DUFFEL BAG','{CategoryId}'),
                (NEWID(), N'JUMP SUIT','{CategoryId}'),
                (NEWID(), N'Colour Pencil','{CategoryId}'),
                (NEWID(), N'Blouse','{CategoryId}'),
                (NEWID(), N'Cotton buds','{CategoryId}'),
                (NEWID(), N'Vehicle','{CategoryId}'),
                (NEWID(), N'PETROLEIUM JELLY','{CategoryId}'),
                (NEWID(), N'GLUE','{CategoryId}'),
                (NEWID(), N'Tissue Holder','{CategoryId}'),
                (NEWID(), N'SOAP HOLDER','{CategoryId}'),
                (NEWID(), N'NULL','{CategoryId}'),
                (NEWID(), N'PUNCHING BAG','{CategoryId}'),
                (NEWID(), N'CLOCK','{CategoryId}'),
                (NEWID(), N'Pant','{CategoryId}'),
                (NEWID(), N'Deo Spray','{CategoryId}'),
                (NEWID(), N'Dressing gown','{CategoryId}'),
                (NEWID(), N'Waist coat','{CategoryId}'),
                (NEWID(), N'Facial cream','{CategoryId}'),
                (NEWID(), N'Sapphire Nail','{CategoryId}'),
                (NEWID(), N'PAPER CUTTER','{CategoryId}'),
                (NEWID(), N'Tank top','{CategoryId}'),
                (NEWID(), N'Trouser material','{CategoryId}'),
                (NEWID(), N'ICE CUBE','{CategoryId}'),
                (NEWID(), N'BIBS','{CategoryId}'),
                (NEWID(), N'Night Pant','{CategoryId}'),
                (NEWID(), N'Mascara','{CategoryId}'),
                (NEWID(), N'BABY WEIGHT MEASURING SUPPORTER','{CategoryId}'),
                (NEWID(), N'Lehenga choli','{CategoryId}'),
                (NEWID(), N'WASH CLOTH','{CategoryId}'),
                (NEWID(), N'MASK','{CategoryId}'),
                (NEWID(), N'Bracelet','{CategoryId}'),
                (NEWID(), N'MEDICINE DISPENSER','{CategoryId}'),
                (NEWID(), N'ASH TRAY','{CategoryId}'),
                (NEWID(), N'Mosquito net','{CategoryId}'),
                (NEWID(), N'SPICE BOTTLE','{CategoryId}'),
                (NEWID(), N'Sarong','{CategoryId}'),
                (NEWID(), N'LIP MOUSSE','{CategoryId}'),
                (NEWID(), N'TABLE RUNNER','{CategoryId}'),
                (NEWID(), N'Corset set','{CategoryId}'),
                (NEWID(), N'Flip Flops','{CategoryId}'),
                (NEWID(), N'Hand Towel','{CategoryId}'),
                (NEWID(), N'SWIMINING ACCESSORIES','{CategoryId}'),
                (NEWID(), N'SKORT','{CategoryId}'),
                (NEWID(), N'KNIFE SHARPNER','{CategoryId}'),
                (NEWID(), N'Eye Brow','{CategoryId}'),
                (NEWID(), N'SPICE CRUSHER','{CategoryId}'),
                (NEWID(), N'VEGETABLE CORER','{CategoryId}'),
                (NEWID(), N'HEAT PAD','{CategoryId}'),
                (NEWID(), N'FOIL BOX','{CategoryId}'),
                (NEWID(), N'Tie','{CategoryId}'),
                (NEWID(), N'Eye Shadow','{CategoryId}'),
                (NEWID(), N'ARM BAND','{CategoryId}'),
                (NEWID(), N'Plate Stand','{CategoryId}'),
                (NEWID(), N'MEDICINE BOX','{CategoryId}'),
                (NEWID(), N'Corset top','{CategoryId}'),
                (NEWID(), N'Safety pin','{CategoryId}'),
                (NEWID(), N'BABY HEAD PROTECTOR','{CategoryId}'),
                (NEWID(), N'BRA','{CategoryId}'),
                (NEWID(), N'Nail Color Remover','{CategoryId}'),
                (NEWID(), N'Underwear','{CategoryId}'),
                (NEWID(), N'NAIL SHINER KIT','{CategoryId}'),
                (NEWID(), N'Side Bag','{CategoryId}'),
                (NEWID(), N'Glass Cup','{CategoryId}'),
                (NEWID(), N'GARLIC CRUSHER','{CategoryId}'),
                (NEWID(), N'Sanitary pad','{CategoryId}'),
                (NEWID(), N'Sandals-B','{CategoryId}'),
                (NEWID(), N'Rippon flower','{CategoryId}'),
                (NEWID(), N'Cleanser','{CategoryId}'),
                (NEWID(), N'CLEANSING SPONGE','{CategoryId}'),
                (NEWID(), N'Body  wash','{CategoryId}'),
                (NEWID(), N'Hand Band','{CategoryId}'),
                (NEWID(), N'Emery Board','{CategoryId}'),
                (NEWID(), N'BACK BOARD','{CategoryId}'),
                (NEWID(), N'Cushioned Long Life','{CategoryId}'),
                (NEWID(), N'Light cream','{CategoryId}'),
                (NEWID(), N'Stool','{CategoryId}'),
                (NEWID(), N'KITCHEN TOWEL','{CategoryId}'),
                (NEWID(), N'Knife','{CategoryId}'),
                (NEWID(), N'Conditioner','{CategoryId}'),
                (NEWID(), N'Eyelash','{CategoryId}'),
                (NEWID(), N'Face wash','{CategoryId}'),
                (NEWID(), N'Hair peg','{CategoryId}'),
                (NEWID(), N'HOT BOTTLE','{CategoryId}'),
                (NEWID(), N'Sunglass','{CategoryId}'),
                (NEWID(), N'MILK PAN','{CategoryId}'),
                (NEWID(), N'Container Set','{CategoryId}'),
                (NEWID(), N'SCOOPER','{CategoryId}'),
                (NEWID(), N'Quilt set','{CategoryId}'),
                (NEWID(), N'Capri pant','{CategoryId}'),
                (NEWID(), N'PILLOW MEDICINE','{CategoryId}'),
                (NEWID(), N'Bottle Opener','{CategoryId}'),
                (NEWID(), N'Bath Towel','{CategoryId}'),
                (NEWID(), N'POPSICLE MOULD','{CategoryId}'),
                (NEWID(), N'Basket','{CategoryId}'),
                (NEWID(), N'CAKE MOULD','{CategoryId}'),
                (NEWID(), N'Towel Set','{CategoryId}'),
                (NEWID(), N'HAIR BUN','{CategoryId}'),
                (NEWID(), N'Office Bag','{CategoryId}'),
                (NEWID(), N'Candle','{CategoryId}'),
                (NEWID(), N'BLACKHEAD REMOVER','{CategoryId}'),
                (NEWID(), N'Tube top','{CategoryId}'),
                (NEWID(), N'Nail Polish','{CategoryId}'),
                (NEWID(), N'TIGHTS','{CategoryId}'),
                (NEWID(), N'Tablet Box','{CategoryId}'),
                (NEWID(), N'Shave Foam','{CategoryId}'),
                (NEWID(), N'PILLOW','{CategoryId}'),
                (NEWID(), N'Swing','{CategoryId}'),
                (NEWID(), N'SLING BAG','{CategoryId}'),
                (NEWID(), N'Arm Flotes','{CategoryId}'),
                (NEWID(), N'Bra&Panty set','{CategoryId}'),
                (NEWID(), N'Cuticle Trimmer','{CategoryId}'),
                (NEWID(), N'Bath Mat','{CategoryId}'),
                (NEWID(), N'LIP BALM','{CategoryId}'),
                (NEWID(), N'Cosmetic Brush Set','{CategoryId}'),
                (NEWID(), N'Maternity pant','{CategoryId}'),
                (NEWID(), N'Bib','{CategoryId}'),
                (NEWID(), N'Storage Bottle','{CategoryId}'),
                (NEWID(), N'FLOOR MAT','{CategoryId}'),
                (NEWID(), N'Hat','{CategoryId}'),
                (NEWID(), N'Key tag','{CategoryId}'),
                (NEWID(), N'Float','{CategoryId}'),
                (NEWID(), N'FEEDING PILLOW','{CategoryId}'),
                (NEWID(), N'SLEEPING BAG','{CategoryId}'),
                (NEWID(), N'Scissor','{CategoryId}'),
                (NEWID(), N'CHARACTER TOY','{CategoryId}'),
                (NEWID(), N'Short type','{CategoryId}'),
                (NEWID(), N'Boy short','{CategoryId}'),
                (NEWID(), N'DAY & NIGHT CREAM','{CategoryId}'),
                (NEWID(), N'Sports bra','{CategoryId}'),
                (NEWID(), N'SIDE BAG-G','{CategoryId}'),
                (NEWID(), N'CRUS SUPPORT','{CategoryId}'),
                (NEWID(), N'Pool','{CategoryId}'),
                (NEWID(), N'ALOE VERA GEL','{CategoryId}'),
                (NEWID(), N'Stationery set','{CategoryId}'),
                (NEWID(), N'Short','{CategoryId}'),
                (NEWID(), N'Jewellery Set','{CategoryId}'),
                (NEWID(), N'LUNCH BAG','{CategoryId}'),
                (NEWID(), N'COOKWARE SET','{CategoryId}'),
                (NEWID(), N'SHOE HORN','{CategoryId}'),
                (NEWID(), N'BURKINI','{CategoryId}'),
                (NEWID(), N'T-Shirt Bra','{CategoryId}'),
                (NEWID(), N'Tumbler','{CategoryId}'),
                (NEWID(), N'Scrub','{CategoryId}'),
                (NEWID(), N'Baby oil','{CategoryId}'),
                (NEWID(), N'Soft Toy','{CategoryId}'),
                (NEWID(), N'Cot sheet','{CategoryId}'),
                (NEWID(), N'FRAGRANCE DIFFUSER','{CategoryId}'),
                (NEWID(), N'Moisturizing cream','{CategoryId}'),
                (NEWID(), N'TOOL BOX','{CategoryId}'),
                (NEWID(), N'Pillow & pillow cover','{CategoryId}'),
                (NEWID(), N'MAKE-UP BRUSH','{CategoryId}'),
                (NEWID(), N'Dungaree','{CategoryId}'),
                (NEWID(), N'HAIR COLOUR','{CategoryId}'),
                (NEWID(), N'Saree Blouse','{CategoryId}'),
                (NEWID(), N'DIVIDED PLATTER','{CategoryId}'),
                (NEWID(), N'Night shirt','{CategoryId}'),
                (NEWID(), N'Maternity panty','{CategoryId}'),
                (NEWID(), N'IMPULSE TOY','{CategoryId}'),
                (NEWID(), N'NAIL LACQUER REMOVER','{CategoryId}'),
                (NEWID(), N'Facial Mask','{CategoryId}'),
                (NEWID(), N'SHOWER CAP','{CategoryId}'),
                (NEWID(), N'SPOON SET','{CategoryId}'),
                (NEWID(), N'Tweezer','{CategoryId}'),
                (NEWID(), N'Body spray','{CategoryId}'),
                (NEWID(), N'Bed jacket','{CategoryId}'),
                (NEWID(), N'Chain','{CategoryId}'),
                (NEWID(), N'COOKIE CUTTER','{CategoryId}'),
                (NEWID(), N'Jegging','{CategoryId}'),
                (NEWID(), N'Teenage bra','{CategoryId}'),
                (NEWID(), N'rain suit','{CategoryId}'),
                (NEWID(), N'Hand Bag','{CategoryId}'),
                (NEWID(), N'JUG WITH CUP','{CategoryId}'),
                (NEWID(), N'Bowl','{CategoryId}'),
                (NEWID(), N'FULL KIT','{CategoryId}'),
                (NEWID(), N'Serviette','{CategoryId}'),
                (NEWID(), N'NOSE STUD','{CategoryId}'),
                (NEWID(), N'SWIMINING KIT','{CategoryId}'),
                (NEWID(), N'Anklets','{CategoryId}'),
                (NEWID(), N'Lotion','{CategoryId}'),
                (NEWID(), N'Gift set','{CategoryId}'),
                (NEWID(), N'Tools Set','{CategoryId}'),
                (NEWID(), N'SPICE SET','{CategoryId}'),
                (NEWID(), N'Over coat','{CategoryId}'),
                (NEWID(), N'Table cloth','{CategoryId}'),
                (NEWID(), N'SERVER','{CategoryId}'),
                (NEWID(), N'Alice Band','{CategoryId}'),
                (NEWID(), N'Eye Fabuliner','{CategoryId}'),
                (NEWID(), N'Play suit','{CategoryId}'),
                (NEWID(), N'Trunk','{CategoryId}'),
                (NEWID(), N'Scarf','{CategoryId}'),
                (NEWID(), N'Nail sharpener','{CategoryId}'),
                (NEWID(), N'Maternity Top','{CategoryId}'),
                (NEWID(), N'Cup & Saucer','{CategoryId}'),
                (NEWID(), N'WALL CLOCK','{CategoryId}'),
                (NEWID(), N'SPOON STAND','{CategoryId}'),
                (NEWID(), N'BAG CLIP','{CategoryId}'),
                (NEWID(), N'Hair mask','{CategoryId}'),
                (NEWID(), N'PENCIL','{CategoryId}'),
                (NEWID(), N'Moisturizer','{CategoryId}'),
                (NEWID(), N'CHARGER','{CategoryId}'),
                (NEWID(), N'DUST PAD','{CategoryId}'),
                (NEWID(), N'JEANS','{CategoryId}'),
                (NEWID(), N'Shoes -U','{CategoryId}'),
                (NEWID(), N'Nappy','{CategoryId}'),
                (NEWID(), N'BLACKHEAD & WHITEHEAD REMOVER','{CategoryId}'),
                (NEWID(), N'TOILETRY BAG','{CategoryId}'),
                (NEWID(), N'Top','{CategoryId}'),
                (NEWID(), N'Body milk','{CategoryId}'),
                (NEWID(), N'Wormer bag','{CategoryId}'),
                (NEWID(), N'Lungi Kit','{CategoryId}'),
                (NEWID(), N'Bag','{CategoryId}'),
                (NEWID(), N'Powder Brush','{CategoryId}'),
                (NEWID(), N'LOAF PAN','{CategoryId}'),
                (NEWID(), N'Baby cream','{CategoryId}'),
                (NEWID(), N'WAIST BAG','{CategoryId}'),
                (NEWID(), N'Head band','{CategoryId}'),
                (NEWID(), N'KURTA SET','{CategoryId}'),
                (NEWID(), N'NIGHT SHORT','{CategoryId}'),
                (NEWID(), N'Body mist','{CategoryId}'),
                (NEWID(), N'CUTTER','{CategoryId}'),
                (NEWID(), N'Sports Kit','{CategoryId}'),
                (NEWID(), N'Mug','{CategoryId}'),
                (NEWID(), N'TOOTHPICK','{CategoryId}'),
                (NEWID(), N'Toner','{CategoryId}'),
                (NEWID(), N'EAR PICK','{CategoryId}'),
                (NEWID(), N'Wallet-C','{CategoryId}'),
                (NEWID(), N'FONDANT PUNCHER','{CategoryId}'),
                (NEWID(), N'Bottom','{CategoryId}'),
                (NEWID(), N'CONTAINER','{CategoryId}'),
                (NEWID(), N'Comb','{CategoryId}'),
                (NEWID(), N'WINTER SUIT','{CategoryId}'),
                (NEWID(), N'Flip Flops -U','{CategoryId}'),
                (NEWID(), N'NECK REST','{CategoryId}'),
                (NEWID(), N'Hanger','{CategoryId}'),
                (NEWID(), N'Blazer','{CategoryId}'),
                (NEWID(), N'Gift Box','{CategoryId}'),
                (NEWID(), N'Stockings','{CategoryId}'),
                (NEWID(), N'MOTAR & PESTLE','{CategoryId}'),
                (NEWID(), N'Breast pad','{CategoryId}'),
                (NEWID(), N'Baby Booty','{CategoryId}'),
                (NEWID(), N'Oil Pitcher','{CategoryId}'),
                (NEWID(), N'Slide','{CategoryId}'),
                (NEWID(), N'Corn plane','{CategoryId}'),
                (NEWID(), N'Shower gel','{CategoryId}'),
                (NEWID(), N'Neet','{CategoryId}'),
                (NEWID(), N'House coat','{CategoryId}'),
                (NEWID(), N'CLEANING CLOTH','{CategoryId}'),
                (NEWID(), N'Compact Make','{CategoryId}'),
                (NEWID(), N'Bottle brush','{CategoryId}'),
                (NEWID(), N'Socks','{CategoryId}'),
                (NEWID(), N'PUMP','{CategoryId}'),
                (NEWID(), N'CORRECTION TAPE','{CategoryId}'),
                (NEWID(), N'FACE SHIELD','{CategoryId}'),
                (NEWID(), N'Feeding set','{CategoryId}'),
                (NEWID(), N'PIZZA CUTTER','{CategoryId}'),
                (NEWID(), N'Pinafore','{CategoryId}'),
                (NEWID(), N'STORAGE RACK','{CategoryId}'),
                (NEWID(), N'Toe Separator','{CategoryId}'),
                (NEWID(), N'Pillow case','{CategoryId}'),
                (NEWID(), N'TONG','{CategoryId}'),
                (NEWID(), N'LIP LINER','{CategoryId}'),
                (NEWID(), N'PAN','{CategoryId}'),
                (NEWID(), N'Cap','{CategoryId}'),
                (NEWID(), N'Pocket Mirror','{CategoryId}'),
                (NEWID(), N'Bangle','{CategoryId}'),
                (NEWID(), N'BOARD SHORT','{CategoryId}'),
                (NEWID(), N'PLATE RACK','{CategoryId}'),
                (NEWID(), N'HAIR BRUSH','{CategoryId}'),
                (NEWID(), N'Thong','{CategoryId}'),
                (NEWID(), N'HAIR ACC SET','{CategoryId}'),
                (NEWID(), N'PRAYER DRESS','{CategoryId}'),
                (NEWID(), N'CLOTHING WASH','{CategoryId}'),
                (NEWID(), N'Foot care cream','{CategoryId}'),
                (NEWID(), N'Sports Toy','{CategoryId}'),
                (NEWID(), N'Plate','{CategoryId}'),
                (NEWID(), N'PLATIGNUM','{CategoryId}'),
                (NEWID(), N'STICKER','{CategoryId}'),
                (NEWID(), N'SHOE INSOLE','{CategoryId}'),
                (NEWID(), N'Eye Remover','{CategoryId}'),
                (NEWID(), N'Swim vest','{CategoryId}'),
                (NEWID(), N'Strainer','{CategoryId}'),
                (NEWID(), N'Glose Serum','{CategoryId}'),
                (NEWID(), N'Salwar material','{CategoryId}'),
                (NEWID(), N'Bottle','{CategoryId}'),
                (NEWID(), N'Jumper','{CategoryId}'),
                (NEWID(), N'FOOD PICK','{CategoryId}'),
                (NEWID(), N'BOTTLE WASH LIQUID','{CategoryId}'),
                (NEWID(), N'COT','{CategoryId}'),
                (NEWID(), N'HAIR ROLLER','{CategoryId}'),
                (NEWID(), N'Dress','{CategoryId}'),
                (NEWID(), N'Diving kit','{CategoryId}'),
                (NEWID(), N'CARD','{CategoryId}'),
                (NEWID(), N'PEN','{CategoryId}'),
                (NEWID(), N'Face Towel','{CategoryId}'),
                (NEWID(), N'Beach Toy','{CategoryId}'),
                (NEWID(), N'TABLE MAT','{CategoryId}'),
                (NEWID(), N'Peeler','{CategoryId}'),
                (NEWID(), N'SWIM SET','{CategoryId}'),
                (NEWID(), N'Nail Cutter','{CategoryId}'),
                (NEWID(), N'PLAY GYM','{CategoryId}'),
                (NEWID(), N'Baby shampoo','{CategoryId}'),
                (NEWID(), N'Shawl','{CategoryId}'),
                (NEWID(), N'Cutting Board','{CategoryId}'),
                (NEWID(), N'Winter Jacket','{CategoryId}'),
                (NEWID(), N'Juice Feeder','{CategoryId}'),
                (NEWID(), N'ADVENTURE TOY','{CategoryId}'),
                (NEWID(), N'Comforter','{CategoryId}'),
                (NEWID(), N'Mackintosh','{CategoryId}'),
                (NEWID(), N'Hair clip','{CategoryId}'),
                (NEWID(), N'PROTECTIVE HAT','{CategoryId}'),
                (NEWID(), N'FABRIC PAINT','{CategoryId}'),
                (NEWID(), N'MAKE-UP BRUSH SET','{CategoryId}'),
                (NEWID(), N'Romper','{CategoryId}'),
                (NEWID(), N'Body lotion','{CategoryId}'),
                (NEWID(), N'Face cream','{CategoryId}'),
                (NEWID(), N'Deep cleansing milk','{CategoryId}'),
                (NEWID(), N'Thermal wear','{CategoryId}'),
                (NEWID(), N'BATH SCRAB','{CategoryId}'),
                (NEWID(), N'Scooter','{CategoryId}'),
                (NEWID(), N'Eye Brow Pencil','{CategoryId}'),
                (NEWID(), N'EYE BROW RAZOR','{CategoryId}'),
                (NEWID(), N'Teether','{CategoryId}'),
                (NEWID(), N'Baby Shirt','{CategoryId}'),
                (NEWID(), N'Toe ring','{CategoryId}'),
                (NEWID(), N'ABAYA','{CategoryId}'),
                (NEWID(), N'Kurta','{CategoryId}'),
                (NEWID(), N'Dish','{CategoryId}'),
                (NEWID(), N'Vacum Bottle','{CategoryId}'),
                (NEWID(), N'Bra panty set','{CategoryId}'),
                (NEWID(), N'Nail clipper','{CategoryId}'),
                (NEWID(), N'CLOTH PEG','{CategoryId}'),
                (NEWID(), N'Wool Band','{CategoryId}'),
                (NEWID(), N'ROLLING PIN','{CategoryId}'),
                (NEWID(), N'SAUCE BOTTLE','{CategoryId}'),
                (NEWID(), N'Shirt','{CategoryId}'),
                (NEWID(), N'Top speed Woman','{CategoryId}'),
                (NEWID(), N'Fork','{CategoryId}'),
                (NEWID(), N'Pijama set','{CategoryId}'),
                (NEWID(), N'Brooch','{CategoryId}'),
                (NEWID(), N'WOK','{CategoryId}'),
                (NEWID(), N'Nail Brush','{CategoryId}'),
                (NEWID(), N'HAND SOCKS','{CategoryId}'),
                (NEWID(), N'Jewelry set','{CategoryId}'),
                (NEWID(), N'Watch Box','{CategoryId}'),
                (NEWID(), N'Nail Polish Remover','{CategoryId}'),
                (NEWID(), N'Top speed Hair Color','{CategoryId}'),
                (NEWID(), N'T&G Pressed Powder','{CategoryId}'),
                (NEWID(), N'Grinder Set','{CategoryId}'),
                (NEWID(), N'FILE POUCH','{CategoryId}'),
                (NEWID(), N'SANITIZER','{CategoryId}'),
                (NEWID(), N'Flask','{CategoryId}'),
                (NEWID(), N'Rattle set','{CategoryId}'),
                (NEWID(), N'PLAY PEN','{CategoryId}'),
                (NEWID(), N'Baby Lotion','{CategoryId}'),
                (NEWID(), N'Kids Towel','{CategoryId}'),
                (NEWID(), N'HOBBY TOY','{CategoryId}'),
                (NEWID(), N'Wrapping Paper','{CategoryId}'),
                (NEWID(), N'Watch','{CategoryId}'),
                (NEWID(), N'Poncho','{CategoryId}'),
                (NEWID(), N'SOAP DISPENSER','{CategoryId}'),
                (NEWID(), N'Oil Pastel','{CategoryId}'),
                (NEWID(), N'FILE','{CategoryId}'),
                (NEWID(), N'POSTER COLOUR','{CategoryId}'),
                (NEWID(), N'Water bottle','{CategoryId}'),
                (NEWID(), N'NOTE BOOK','{CategoryId}'),
                (NEWID(), N'Three Quarter','{CategoryId}'),
                (NEWID(), N'Pedicure Brush','{CategoryId}'),
                (NEWID(), N'Cap & Socks','{CategoryId}'),
                (NEWID(), N'Bra strap','{CategoryId}'),
                (NEWID(), N'Umbrella','{CategoryId}'),
                (NEWID(), N'Bow tie','{CategoryId}'),
                (NEWID(), N'Saree','{CategoryId}'),
                (NEWID(), N'Battery','{CategoryId}'),
                (NEWID(), N'WRIST SUPPORT','{CategoryId}'),
                (NEWID(), N'NAPPY HOLDER','{CategoryId}'),
                (NEWID(), N'COMPACT','{CategoryId}'),
                (NEWID(), N'PULL BUOY','{CategoryId}'),
                (NEWID(), N'Doll','{CategoryId}'),
                (NEWID(), N'MEDICINE FEEDER','{CategoryId}'),
                (NEWID(), N'POTTY SEAT','{CategoryId}'),
                (NEWID(), N'Skirt','{CategoryId}'),
                (NEWID(), N'Brush','{CategoryId}'),
                (NEWID(), N'Mesh Body Sponge','{CategoryId}'),
                (NEWID(), N'Sports','{CategoryId}'),
                (NEWID(), N'Bonnet','{CategoryId}'),
                (NEWID(), N'BABY BATH CHAIR','{CategoryId}'),
                (NEWID(), N'Tooth brush','{CategoryId}'),
                (NEWID(), N'Breast pump','{CategoryId}'),
                (NEWID(), N'Pencil box','{CategoryId}'),
                (NEWID(), N'Cellulose Cleansing','{CategoryId}'),
                (NEWID(), N'Quilt','{CategoryId}'),
                (NEWID(), N'Choli kit','{CategoryId}'),
                (NEWID(), N'Food maker','{CategoryId}'),
                (NEWID(), N'Nail Enamel','{CategoryId}'),
                (NEWID(), N'Table','{CategoryId}'),
                (NEWID(), N'Nighty','{CategoryId}'),
                (NEWID(), N'Foot care','{CategoryId}'),
                (NEWID(), N'FLOWERS','{CategoryId}'),
                (NEWID(), N'Shoes-G','{CategoryId}'),
                (NEWID(), N'ALUMINIUM FOIL','{CategoryId}'),
                (NEWID(), N'FONDANT IMPRINTER','{CategoryId}'),
                (NEWID(), N'After shave','{CategoryId}'),
                (NEWID(), N'Day cream','{CategoryId}'),
                (NEWID(), N'PENCIL REFILL LEAD','{CategoryId}'),
                (NEWID(), N'COLOUR STAY MAKE UP','{CategoryId}'),
                (NEWID(), N'Tissue Box','{CategoryId}'),
                (NEWID(), N'Raincoat','{CategoryId}'),
                (NEWID(), N'Training cup','{CategoryId}'),
                (NEWID(), N'Wet Wipes','{CategoryId}'),
                (NEWID(), N'BEATER','{CategoryId}'),
                (NEWID(), N'Eye Liner Pencil','{CategoryId}'),
                (NEWID(), N'Winter Glove','{CategoryId}'),
                (NEWID(), N'Clutch','{CategoryId}'),
                (NEWID(), N'SAUCE PAN','{CategoryId}'),
                (NEWID(), N'Bra cup','{CategoryId}'),
                (NEWID(), N'POWDER','{CategoryId}'),
                (NEWID(), N'Color N Care','{CategoryId}'),
                (NEWID(), N'ICING NOZZLES','{CategoryId}'),
                (NEWID(), N'Retractable','{CategoryId}'),
                (NEWID(), N'CUSHION & COVER','{CategoryId}'),
                (NEWID(), N'Knee pad','{CategoryId}'),
                (NEWID(), N'Panty','{CategoryId}'),
                (NEWID(), N'Sandals-G','{CategoryId}'),
                (NEWID(), N'SWIM CAP','{CategoryId}'),
                (NEWID(), N'Soap','{CategoryId}'),
                (NEWID(), N'Haram Pant','{CategoryId}'),
                (NEWID(), N'Wrapping Bag','{CategoryId}'),
                (NEWID(), N'VITAMIN E CREAM','{CategoryId}'),
                (NEWID(), N'Sweater','{CategoryId}'),
                (NEWID(), N'Deo Stick','{CategoryId}'),
                (NEWID(), N'Scale','{CategoryId}'),
                (NEWID(), N'PENCIL PURSE','{CategoryId}'),
                (NEWID(), N'JUICER','{CategoryId}'),
                (NEWID(), N'Salwar Top','{CategoryId}'),
                (NEWID(), N'FITTED SHEET','{CategoryId}'),
                (NEWID(), N'FOOD PRESERVATION BAGS','{CategoryId}'),
                (NEWID(), N'ORGANIZER BAG','{CategoryId}'),
                (NEWID(), N'COLOR BURST MATTE BALM','{CategoryId}'),
                (NEWID(), N'PALM SUPPORT','{CategoryId}'),
                (NEWID(), N'Three Ring Pool','{CategoryId}'),
                (NEWID(), N'BRA ACCESSORIES','{CategoryId}'),
                (NEWID(), N'Foot file','{CategoryId}'),
                (NEWID(), N'Baby cologne','{CategoryId}'),
                (NEWID(), N'Nipple','{CategoryId}'),
                (NEWID(), N'EYE GEL','{CategoryId}'),
                (NEWID(), N'BAKING PAPER','{CategoryId}'),
                (NEWID(), N'BURP CLOTH','{CategoryId}'),
                (NEWID(), N'Hair Wrap','{CategoryId}'),
                (NEWID(), N'Bottle handle','{CategoryId}'),
                (NEWID(), N'BATH TUB','{CategoryId}'),
                (NEWID(), N'BACK PACK-L','{CategoryId}'),
                (NEWID(), N'Jug','{CategoryId}'),
                (NEWID(), N'Girdle belt','{CategoryId}'),
                (NEWID(), N'Feeding bottle','{CategoryId}'),
                (NEWID(), N'Eye Cream','{CategoryId}'),
                (NEWID(), N'PIMPLE POWDER PACK','{CategoryId}'),
                (NEWID(), N'CAKE SCRAPER','{CategoryId}'),
                (NEWID(), N'Career bag','{CategoryId}'),
                (NEWID(), N'POTTY','{CategoryId}'),
                (NEWID(), N'PHOTO READY','{CategoryId}'),
                (NEWID(), N'FURNITURE PROTECTOR','{CategoryId}'),
                (NEWID(), N'POOL BED','{CategoryId}'),
                (NEWID(), N'Skinny','{CategoryId}'),
                (NEWID(), N'Blush Brush','{CategoryId}'),
                (NEWID(), N'Whitening Cream','{CategoryId}'),
                (NEWID(), N'HOLDER','{CategoryId}'),
                (NEWID(), N'NIGHTY SET','{CategoryId}'),
                (NEWID(), N'Ring','{CategoryId}'),
                (NEWID(), N'TENDERIZER','{CategoryId}'),
                (NEWID(), N'Soother','{CategoryId}');");
        }
        private void SeedClaims(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [AspNetRoleClaims] (RoleId, ClaimType, ClaimValue)
                VALUES ('{AdminRoleId}', 'Permission', 'RequireAdmin');");
        }
        private void SeedMenu(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [Menu] (MenuId, DisplayName, sort) VALUES 
                ('{employeeMenu}', 'Employee', 1),  
                ('{userMenu}', 'User', 2),
                ('{categoryMenu}', 'Category', 3),
                ('{menu}', 'Menu', 5),
                ('{subcategoryMenu}', 'Sub Category', 4);");
        }
        private void SeedSubMenu(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [SubMenu] (SubMenuId, DisplayName, Controller, Method, MenuId) VALUES 
                    ('{createEmployeeSubMenu}', 'Create Employee', 'Employee', 'Create', '{employeeMenu}'),
                    ('{listEmployeeSubMenu}', 'List Employee', 'Employee', 'List', '{employeeMenu}'),
                    (NEWID(), 'Register', 'User', 'Register', '{userMenu}'),
                    (NEWID(), 'List', 'User', 'Index', '{userMenu}'),
                    ('{profileUserSubMenu}', 'Profile', 'User', 'Profile', '{userMenu}'),
                    (NEWID(), 'Create', 'Category', 'Index', '{categoryMenu}'),
                    (NEWID(), 'Create', 'SubCategory', 'Index', '{subcategoryMenu}'),
                    (NEWID(), 'Create menu', 'SubMenu', 'Index', '{menu}'),
                    (NEWID(), 'Mapping', 'CategorySubCategoryMapping', 'Index', '{subcategoryMenu}');");
        }
        private void SeedSubMenuRole(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"
                INSERT INTO [SubMenuRoles] (SubMenuId, Id) VALUES 
                    ('{createEmployeeSubMenu}','{UserRoleId}'),
                    ('{listEmployeeSubMenu}','{UserRoleId}');");
        }
    }
}
